general:
  github_repo_url: "https://github.com/codingpot/newsletter_awesome_articles"
  git_branch: "main"

email:
  title: "코딩맛집 뉴스레터"
  footer_title: "코딩맛집"
  receivers:
    - "deep.diver.csp@gmail.com"
  header_title: "코딩맛집에서 발행하는 뉴스레터 입니다"
  header_description: "재밌게 봐주십쇼!"
  header_image_url: "https://i.ibb.co/7k7Cs9x/codingpot-logo.png"
  community_link: "https://discord.gg/HGPnfzDdkG"
  community_link_btn_title: "커뮤니티 둘러보고 가입하러 가기"
  section_title: "유용한 자료 요약 및 링크"
  content_link_btn_title: "원문으로 이동하기"
  bgcolor: "#aad7ef"