general:
  github_repo_url: "https://github.com/codingpot/newsletter_awesome_articles"
  git_branch: "main"

email:
  title: "email title"
  footer_title: "email footer title"
  receivers:
    - receiver1
    - receiver2
  header_title: "newsletter name"
  header_description: "have a good read!"
  header_image_url: "https://..."
  community_link: "https://..."
  community_link_btn_title: "title of the link to your community"
  section_title: "what information does this newsletter deliver?"
  content_link_btn_title: "title of the buttn to show in each content"
  bgcolor: "orange"
