name: send_newsletter

on:
  workflow_dispatch:

#   push:
#     branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Check how many 
        id: number_check
        run: |
          echo "::set-output name=number::$(ls current/*.yaml | wc -l)"

      - name: Set up Go
        if: steps.number_check.outputs.number == 6
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      # Runs a single command using the runners shell
      - name: Send Newsletter
        if: steps.number_check.outputs.number == 6      
        env: 
          EMAIL: ${{ secrets.EMAIL }}
          PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: cd ./src && go run main.go publish current
        
      - name: Commit Changes
        if: steps.number_check.outputs.number == 6      
        run: |
          git config --global user.name 'Chansung'
          git config --global user.email 'deep.diver.csp@gmail.com'
          git add .
          git commit -m "Automated report"
          git push
